language: python
python:
  - "2.7"
env:
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install -q -e . --use-mirrors
before_script:
  - "pep8 --exclude=tests,migrations --ignore=E124,E128 documents"
script:
  - python setup.py test
